[package]
name = "win2d_fail"
version = "0.1.0"
authors = ["Michael Ilyin <milyin@gmail.com>"]
edition = "2018"

[dependencies]
winrt = "0.7.1"

[package.metadata.winrt.dependencies]
"Win2D.uwp" = "1.25.0"
